#macro MEDAL_VERBOSE  MEDAL_RUNNING_FROM_IDE

#macro MEDAL_FORCE_LOCAL  false

enum MEDAL
{
    SHINY_MACGUFFIN,
    SLAY_FIFTY_THOUSAND_RATS,
    OBNOXIOUS_JUMPING_PUZZLE,
    WACKY_NPC_INTERACTION,
}